import { ArrowUp, ArrowUpRight, Check, MapPin, Menu, MessageCircle, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import LeadCaptureSection from "@/components/LeadCaptureSection";
import LeadFloatingCta from "@/components/LeadFloatingCta";
import { WHATSAPP, whatsappUrl } from "@/lib/leadIntegration";

export { WHATSAPP, whatsappUrl };

export function Logo() { return <Link href="/" className="brand-logo-link" aria-label="Valentis Solutions — página inicial"><img className="brand-logo-image" src="/assets/valentis-solutions-logo-hd.png" alt="Valentis Solutions" /></Link>; }

const navItems = [{ href: "/", label: "Início" }, { href: "/servicos", label: "Serviços" }, { href: "/sistemas", label: "Sistemas" }, { href: "/diagnostico", label: "Diagnóstico" }, { href: "/planos", label: "Planos" }, { href: "/sobre", label: "Sobre nós" }];

export function Header() {
  const [open, setOpen] = useState(false);
  useEffect(() => { const close = () => setOpen(false); window.addEventListener("resize", close); return () => window.removeEventListener("resize", close); }, []);
  return <><header className="site-header"><div className="container flex min-h-[76px] items-center justify-between"><Logo /><nav className="hidden items-center gap-6 text-sm font-semibold text-[#5c5871] lg:flex" aria-label="Navegação principal">{navItems.map(item => <Link key={item.href} href={item.href} className="transition-colors hover:text-[#3b2e6b]">{item.label}</Link>)}</nav><div className="flex items-center gap-2"><a target="_blank" rel="noopener noreferrer" className="button button-small button-ghost hidden sm:inline-flex" href={whatsappUrl("Olá! Quero entender como a Valentis pode ajudar meu negócio.")}>Falar com a Valentis <ArrowUpRight size={15} /></a><button type="button" aria-label={open ? "Fechar menu" : "Abrir menu"} aria-expanded={open} className="menu-toggle lg:hidden" onClick={() => setOpen(!open)}>{open ? <X size={22} /> : <Menu size={22} />}</button></div></div>{open && <nav className="mobile-menu lg:hidden" aria-label="Navegação mobile">{navItems.map(item => <Link key={item.href} href={item.href} onClick={() => setOpen(false)}>{item.label}<ArrowUpRight size={16} /></Link>)}<a target="_blank" rel="noopener noreferrer" href={whatsappUrl("Olá! Quero falar com a Valentis.")} onClick={() => setOpen(false)}>Falar com a Valentis <MessageCircle size={16} /></a></nav>}</header><LeadFloatingCta /><BackToTop /></>;
}

function BackToTop() { const [visible, setVisible] = useState(false); useEffect(() => { const onScroll = () => setVisible(window.scrollY > 480); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []); return <button type="button" aria-label="Voltar ao topo" title="Voltar ao topo" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className={`back-to-top ${visible ? "back-to-top-visible" : ""}`}><ArrowUp size={18} strokeWidth={2.5} /></button>; }

export function Footer() { return <><LeadCaptureSection /><footer className="border-t border-[#e6e2f1] bg-white"><div className="container grid gap-10 py-12 md:grid-cols-[1.3fr_1fr_1fr]"><div><Logo /><p className="mt-4 max-w-sm text-sm leading-6 text-[#716d80]">Soluções para negócios locais que precisam atrair oportunidades e organizar a operação.</p></div><div><p className="eyebrow mb-4">Explorar</p><div className="grid gap-3 text-sm font-semibold text-[#4e4961]"><Link href="/servicos">Serviços</Link><Link href="/sistemas">Sistemas</Link><Link href="/diagnostico">Diagnóstico</Link><Link href="/planos">Planos</Link><Link href="/sobre">Sobre nós</Link></div></div><div><p className="eyebrow mb-4">Atendimento</p><div className="grid gap-3 text-sm text-[#716d80]"><span className="flex items-center gap-2"><MapPin size={15} className="text-[#7c4fe0]" />Maringá e Sarandi, PR</span><a target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 font-semibold text-[#4e4961]" href={whatsappUrl("Olá! Quero falar sobre as soluções da Valentis.")}><MessageCircle size={15} className="text-[#7c4fe0]" />WhatsApp direto</a></div></div></div><div className="container flex flex-col justify-between gap-3 border-t border-[#eeeaf7] py-5 text-xs text-[#8a8597] sm:flex-row"><span>© 2026 Valentis Solutions.</span><div className="flex flex-wrap gap-x-4 gap-y-2"><Link href="/privacidade">Privacidade</Link><Link href="/termos">Termos de uso</Link><span>Estratégia, tecnologia e clareza para negócios locais.</span></div></div></footer></>; }
export function CheckLine({ children }: { children: React.ReactNode }) { return <li className="flex items-start gap-3 text-sm leading-6 text-[#4e4961]"><span className="mt-1 flex size-4 shrink-0 items-center justify-center rounded-full bg-[#eee9ff] text-[#6542c4]"><Check size={11} strokeWidth={3} /></span>{children}</li>; }
export function SiteChrome() { return <BackToTop />; }
