import { ArrowRight, Check, Compass, HeartHandshake, Lightbulb, Target, Users } from "lucide-react";
import { Link } from "wouter";
import { Footer, Header, whatsappUrl } from "@/components/MarketingLayout";

const principles = [
  { icon: Target, title: "Clareza antes da execução", text: "Antes de sugerir campanhas ou tecnologia, entendemos o problema, a operação e o resultado que precisa ser alcançado." },
  { icon: HeartHandshake, title: "Proximidade responsável", text: "Trabalhamos com comunicação direta, escopo compreensível e alinhamento sobre o que depende de cada lado." },
  { icon: Lightbulb, title: "Soluções proporcionais", text: "Nem todo negócio precisa da ferramenta mais complexa. A melhor solução é a que a operação consegue usar e sustentar." },
  { icon: Users, title: "Construção em parceria", text: "O cliente participa das decisões importantes para que a solução faça sentido na rotina, não apenas na apresentação." },
];

export default function About() {
  return <div className="min-h-screen bg-[#fbfaff] text-[#23202e]"><Header /><main>
    <section className="subhero image-subhero image-subhero-strategy relative overflow-hidden"><div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" /><div className="container relative py-20 md:py-28"><p className="eyebrow"><span className="eyebrow-dot" />Sobre a Valentis</p><h1 className="display-title mt-5 max-w-4xl">Tecnologia e aquisição com <span className="gradient-text">visão de negócio.</span></h1><p className="hero-copy mt-6 max-w-2xl">A Valentis Solutions existe para ajudar negócios locais a transformar desafios de crescimento e organização em próximos passos mais claros.</p></div></section>
    <section className="section-pad bg-white"><div className="container grid items-start gap-12 lg:grid-cols-[.85fr_1.15fr]"><div className="md:sticky md:top-28"><p className="eyebrow"><span className="eyebrow-dot" />Nossa visão</p><h2 className="section-title mt-4">Menos complexidade.<br /><span className="gradient-text">Mais direção.</span></h2></div><div className="max-w-2xl space-y-6 text-[1.05rem] leading-8 text-[#625b73]"><p>Pequenos negócios costumam enfrentar dois desafios conectados: precisam atrair clientes, mas também precisam organizar o que acontece depois que eles chegam.</p><p>Por isso, a Valentis reúne duas frentes complementares: aquisição local, para gerar oportunidades, e sistemas personalizados, para dar mais controle à operação.</p><p>Não acreditamos em soluções prontas para todos. Acreditamos em diagnóstico, escopo claro e evolução compatível com o momento de cada empresa.</p><div className="mt-8 rounded-2xl bg-[#f3f0fc] p-6 text-base font-bold leading-7 text-[#3b2e6b]">“A tecnologia deve tornar a decisão mais simples — não criar mais uma camada de confusão.”</div></div></div></section>
    <section className="section-pad"><div className="container"><div className="section-intro"><div><p className="eyebrow"><span className="eyebrow-dot" />Como pensamos</p><h2 className="section-title mt-4">Princípios que orientam<br /><span className="gradient-text">cada projeto.</span></h2></div><p className="section-lead">O trabalho começa antes da ferramenta. Começa na compreensão do cenário.</p></div><div className="principles-grid mt-12">{principles.map(({ icon: Icon, title, text }) => <article className="principle-card" key={title}><span className="principle-icon"><Icon size={21} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section-pad bg-[#1b1533] text-white"><div className="container grid items-center gap-10 md:grid-cols-[1fr_auto]"><div><p className="eyebrow eyebrow-light"><span className="eyebrow-dot" />Vamos conversar</p><h2 className="mt-4 max-w-2xl text-3xl font-black tracking-[-.04em] md:text-5xl">Seu próximo passo pode começar por uma boa pergunta.</h2><p className="mt-5 max-w-xl leading-7 text-white/65">Conte o que está acontecendo na sua operação. A primeira conversa serve para avaliar se existe um caminho coerente para avançar.</p></div><div className="flex flex-col gap-3 sm:flex-row md:flex-col"><Link className="button button-white" href="/diagnostico">Fazer diagnóstico <ArrowRight size={17} /></Link><a className="button border border-white/20 text-white hover:bg-white/10" href={whatsappUrl("Olá! Quero conhecer melhor a Valentis e conversar sobre meu negócio.")}>Falar com a Valentis <ArrowRight size={17} /></a></div></div></section>
  </main><Footer /></div>;
}

