import { ArrowLeft, Gavel, ShieldCheck } from "lucide-react";
import type { ReactNode } from "react";
import { Link } from "wouter";
import { Footer, Header } from "@/components/MarketingLayout";

function LegalShell({ title, eyebrow, icon: Icon, children }: { title: ReactNode; eyebrow: string; icon: typeof ShieldCheck; children: ReactNode }) {
  return <div className="min-h-screen bg-[#fbfaff] text-[#23202e]"><Header /><main><section className="subhero"><div className="container py-16 md:py-24"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-[#6b4ac7]"><ArrowLeft size={16} />Voltar para a home</Link><p className="eyebrow"><span className="eyebrow-dot" />{eyebrow}</p><div className="mt-5 flex max-w-4xl items-start gap-5"><div className="legal-hero-icon"><Icon size={28} /></div><div><h1 className="display-title">{title}</h1><p className="hero-copy mt-6 max-w-2xl">Leia as condições que orientam o uso do site e o relacionamento com a Valentis Solutions.</p></div></div></div></section><section className="section-pad"><article className="container legal-document">{children}</article></section></main><Footer /></div>;
}

export function Privacy() {
  return <LegalShell title={<>Política de <span className="gradient-text">Privacidade.</span></>} eyebrow="Transparência e cuidado" icon={ShieldCheck}>
    <p className="legal-updated">Última atualização: 15 de setembro de 2026</p>
    <h2>1. Compromisso com a privacidade</h2><p>A Valentis Solutions respeita a privacidade de visitantes, leads e clientes. Esta política explica quais informações podem ser coletadas neste site, para quais finalidades e quais escolhas estão disponíveis ao titular dos dados.</p>
    <h2>2. Dados coletados</h2><p>Podemos receber dados fornecidos voluntariamente em formulários, como nome, empresa, segmento, objetivo, informações sobre o momento do negócio e dados de contato. Também podem ser registrados dados técnicos básicos de navegação, como endereço IP, dispositivo, navegador, páginas acessadas e eventos de interação.</p>
    <h2>3. Finalidades de uso</h2><p>Os dados podem ser utilizados para responder solicitações, realizar diagnósticos preliminares, enviar mensagens solicitadas, preparar propostas, prestar serviços, melhorar o site, medir campanhas e proteger a operação contra abuso. Não vendemos dados pessoais.</p>
    <h2>4. WhatsApp e terceiros</h2><p>Quando você escolhe falar conosco pelo WhatsApp, a mensagem e os dados necessários para o contato são tratados também pelos provedores envolvidos. O envio ocorre somente após a sua ação no botão correspondente. Ferramentas de análise e publicidade podem utilizar identificadores técnicos e eventos de conversão conforme suas próprias políticas.</p>
    <h2>5. Base, retenção e compartilhamento</h2><p>O tratamento pode ocorrer com base no consentimento, na execução de medidas solicitadas pelo titular, no cumprimento de obrigações legais ou no legítimo interesse aplicável. Mantemos os dados pelo período necessário à finalidade ou às obrigações correspondentes. O compartilhamento é limitado a fornecedores e plataformas necessários à operação, sempre dentro da finalidade informada.</p>
    <h2>6. Direitos do titular</h2><p>Você pode solicitar confirmação de tratamento, acesso, correção, anonimização, eliminação quando cabível, informação sobre compartilhamentos e revogação do consentimento, observadas as limitações legais. Para exercer esses direitos ou tirar dúvidas, entre em contato pelo WhatsApp disponível no site, informando o pedido com clareza.</p>
    <h2>7. Segurança e limites</h2><p>Adotamos medidas razoáveis de segurança e controle de acesso. Nenhum ambiente digital é completamente imune a incidentes. Caso uma ocorrência relevante afete dados pessoais, adotaremos as medidas aplicáveis e comunicaremos os envolvidos quando necessário.</p>
    <h2>8. Alterações</h2><p>Esta política pode ser atualizada para refletir mudanças no site, nos serviços ou na legislação. A versão vigente será sempre publicada nesta página.</p>
  </LegalShell>;
}

export function Terms() {
  return <LegalShell title={<>Termos de <span className="gradient-text">Uso.</span></>} eyebrow="Regras de relacionamento" icon={Gavel}>
    <p className="legal-updated">Última atualização: 15 de setembro de 2026</p>
    <h2>1. Aceitação</h2><p>Ao acessar sovalentis.com, você declara que leu estes Termos de Uso. Se não concordar com alguma condição, não utilize as áreas e serviços do site. A Valentis Solutions pode atualizar estes termos, mantendo a versão vigente nesta página.</p>
    <h2>2. Finalidade do site</h2><p>O site apresenta serviços de aquisição local, tráfego pago, sistemas personalizados, diagnóstico e soluções complementares. O conteúdo é informativo e não constitui promessa de resultado, proposta irrevogável ou contrato de prestação de serviços.</p>
    <h2>3. Diagnóstico e informações comerciais</h2><p>O diagnóstico é uma triagem inicial baseada nas respostas fornecidas pelo visitante. Qualquer recomendação depende de análise posterior da operação, oferta, região, verba, atendimento, capacidade de entrega e demais condições do negócio. Contratações somente serão válidas após aceite de proposta ou instrumento específico.</p>
    <h2>4. Propriedade intelectual</h2><p>O nome Valentis Solutions, a marca Valentis, seus sinais distintivos, logotipos, identidade visual, textos, imagens, ilustrações, layouts, códigos, componentes, interfaces, materiais comerciais e demais elementos do site pertencem à Valentis Solutions ou são utilizados com autorização. A proteção alcança o conjunto visual e editorial, não apenas elementos isolados.</p><p>É proibido copiar, reproduzir, adaptar, distribuir, publicar, vender, sublicenciar, realizar engenharia reversa ou utilizar comercialmente qualquer elemento do site sem autorização prévia e escrita. O acesso ao site não transfere propriedade, licença comercial ou direito de uso da marca.</p>
    <h2>5. Conteúdo enviado pelo visitante</h2><p>Ao enviar informações, você declara que possui autorização para compartilhá-las e que elas não violam direitos de terceiros. Você permanece responsável pela exatidão e legalidade do material enviado. A Valentis Solutions poderá utilizar essas informações apenas para as finalidades comunicadas e operacionais relacionadas ao atendimento.</p>
    <h2>6. Links, disponibilidade e responsabilidade</h2><p>O site pode conter links para plataformas externas, que possuem termos próprios. Não garantimos disponibilidade contínua, ausência de erros ou compatibilidade com todos os dispositivos. Não nos responsabilizamos por decisões tomadas exclusivamente com base em conteúdo informativo do site, nem por indisponibilidade ou falhas de serviços de terceiros.</p>
    <h2>7. Uso proibido</h2><p>Não é permitido utilizar o site para fraude, tentativa de invasão, coleta automatizada abusiva, distribuição de código malicioso, violação de direitos, envio de conteúdo ilícito ou qualquer conduta que prejudique a operação, a marca ou outros usuários.</p>
    <h2>8. Contato e legislação aplicável</h2><p>Dúvidas, solicitações de autorização e notificações podem ser encaminhadas pelo canal de WhatsApp indicado no site. Estes termos devem ser interpretados conforme a legislação brasileira, sem prejuízo das regras obrigatórias aplicáveis ao consumidor.</p>
  </LegalShell>;
}
